### PR TITLE
fix double-writing masked resources

### LINKED ISSUE #189: Correct double-writing of MASKED_RESOURCES
The MASKED_RESOURCES parameter seems to be getting as many as three copies of masked apps: e.g.
```["HCAL_Laser","hcalLaserController_0","hcal::GapOperationsManager_0","hcal::uMNioManager_0","DummyTriggerAdapter_1","hcalEventBuilder_1","hcalTrivialFU_1","hcalEventBuilder_5","hcalTrivialFU_5","FanoutTTCciTA_0","Executive_18","JobControl","tcds::ici::ICIController_3","tcds::pi::PIController_3","Executive_40","hcalCrate_9","hcal::DTCManager_9","hcal::uHTRManager_9","hcal::GapOperationsManager_0","hcal::uMNioManager_0","hcalLaserController_0","DummyTriggerAdapter_3","hcal::DTCReadout_9","hcalEventBuilder_3","hcalTrivialFU_3","Executive_20","hcalPartitionViewer_3","hcalSupervisor_3","Executive_19","JobControl","hcalRunInfoServer_3","DummyTriggerAdapter_3","hcalEventBuilder_3","hcalTrivialFU_3","hcalEventBuilder_4","DummyTriggerAdapter_4","hcalTrivialFU_4","DummyTriggerAdapter_0","hcalEventBuilder_0","hcalTrivialFU_0","hcalLaserController_0","hcal::GapOperationsManager_0","hcal::uMNioManager_0"]```
This should be fixed.

### PR DESCRIPTION
**Pull request by jhakala**
Hopefully fixes #189. Tested at FNAL, please test further.

### CODE REVIEW

File: src/rcms/fm/app/level1/HCALMasker.java [hunk 1]
```diff
@@ -232,7 +232,9 @@ else if (functionManager.RunType.equals("global")){
               allMaskedResources = (VectorT<StringT>)functionManager.getHCALparameterSet().get("MASKED_RESOURCES").getValue();
               for (Resource level2resource : fullconfigList) {
                 logger.debug("[HCAL " + functionManager.FMname + "]: The masked level 2 function manager " + qr.getName() + " has this in its XdaqExecutive list: " + level2resource.getName());
-                allMaskedResources.add(new StringT(level2resource.getName()));
```
Comment (kakwok) [inline src/rcms/fm/app/level1/HCALMasker.java]: In here, we are adding all childResources of any maskedFM to the `allMaskedResources` (see my comment few lines above)

File: src/rcms/fm/app/level1/HCALMasker.java [hunk 2]
```diff
@@ -266,7 +268,10 @@ else if (functionManager.RunType.equals("global")){
               if (resourceName.contains(EvmTrigName)) {
                 //Mask all EvmTrig apps except for the ones we picked
                 if (!level2resource.getName().equals(eventBuilder) && !level2resource.getName().equals(trivialFU) && !level2resource.getName().equals(triggerAdapter)) { 
-                  allMaskedResources.add(new StringT(resourceName));
```
Comment (kakwok) [inline src/rcms/fm/app/level1/HCALMasker.java]: In here, we add again the all un-picked EvmTrig Apps, which of course, are part of the maskedFM (if any) childResources. Hence the double-writing

**Comment by kakwok** [comment]
For the record, I paste the test result here:
```
Before:
["HCAL_HBHE904","HCAL_HF904","hcalRBXManager_1","hcalRBXManager_2","hcal::GapOperationsManager_0","hcal::uMNioManager_0","Executive_1","hcalSupervisor_0","hcalPartitionViewer_0","Executive_2","hcalRBXManager_0","Executive_3","hcal::DTCManager_0","hcalCrate_0","Executive_4","hcal::DTCReadout_0","hcal::uHTRManager_0","hcal::DTCManager_1","hcalCrate_1","Executive_5","hcal::DTCReadout_1","hcal::uHTRManager_1","hcal::DTCManager_2","hcalCrate_2","Executive_6","hcal::DTCManager_3","hcalCrate_3","hcalTrivialFU_0","hcalEventBuilder_0","hcal::ngRBXSequencer_0","hcal::DTCReadout_2","DummyTriggerAdapter_0","hcal::uHTRManager_2","Executive_7","hcal::ngRBXManager_0","Executive_0","hcalRunInfoServer_0","JobControl","hcalTrivialFU_0","hcalEventBuilder_0","DummyTriggerAdapter_0","Executive_9","hcalRunInfoServer_1","Executive_10","hcalTrivialFU_1","hcalEventBuilder_1","hcal::ngRBXSequencer_1","hcal::DTCReadout_3","DummyTriggerAdapter_1","hcal::uHTRManager_3","hcal::DTCManager_4","hcalCrate_4","Executive_11","hcal::DTCReadout_4","hcal::uHTRManager_4","hcal::DTCManager_5","hcalCrate_5","Executive_12","hcal::ngRBXManager_1","Executive_13","hcalRBXManager_1","Executive_8","hcalSupervisor_1","hcalPartitionViewer_1","JobControl","hcalTrivialFU_1","hcalEventBuilder_1","DummyTriggerAdapter_1"]
```
After:
```
["HCAL_HBHE904","HCAL_HF904","hcalRBXManager_1","hcalRBXManager_2","hcal::GapOperationsManager_0","hcal::uMNioManager_0","Executive_1","hcalSupervisor_0","hcalPartitionViewer_0","Executive_2","hcalRBXManager_0","Executive_3","hcal::DTCManager_0","hcalCrate_0","Executive_4","hcal::DTCReadout_0","hcal::uHTRManager_0","hcal::DTCManager_1","hcalCrate_1","Executive_5","hcal::DTCReadout_1","hcal::uHTRManager_1","hcal::DTCManager_2","hcalCrate_2","Executive_6","hcal::DTCManager_3","hcalCrate_3","hcalTrivialFU_0","hcalEventBuilder_0","hcal::ngRBXSequencer_0","hcal::DTCReadout_2","DummyTriggerAdapter_0","hcal::uHTRManager_2","Executive_7","hcal::ngRBXManager_0","Executive_0","hcalRunInfoServer_0","JobControl","Executive_9","hcalRunInfoServer_1","Executive_10","hcalTrivialFU_1","hcalEventBuilder_1","hcal::ngRBXSequencer_1","hcal::DTCReadout_3","DummyTriggerAdapter_1","hcal::uHTRManager_3","hcal::DTCManager_4","hcalCrate_4","Executive_11","hcal::DTCReadout_4","hcal::uHTRManager_4","hcal::DTCManager_5","hcalCrate_5","Executive_12","hcal::ngRBXManager_1","Executive_13","Executive_8","hcalSupervisor_1","hcalPartitionViewer_1"]
```
